name: "newton_locomotion"
policy: "MlpPolicy"
seed: 75129

num_envs: 4096
timesteps: 100_000
episode_length: 1000 # 20 seconds of real time (2000 * 0.01 = 20)
reset_in_play: True

scalers:
  observations:
    projected_gravities: 1.0
    linear_velocities: 2.0
    angular_velocities: 0.25
    joint_positions: 1.0
    joint_velocities: 0.05
    last_actions: 1.0
    velocity_commands: 1.0

  rewards:
    position: 0.5
    height: 50.0
    base_stability: 2.0
    base_linear_velocity_xy: 1.0
    base_linear_velocity_z: 1.0
    base_angular_velocity_z: 0.5
    joint_positions: 0.1
    joint_action_rate: 0.005
    air_time: 0.5
    survival: 5.0

  action: 1.0

  commands:
    linear_velocity_xy: 1.0
    angular_velocity_z: 1.0

ppo:
  rollouts: 24 # 0.48 seconds of real time (24 * 0.02 = 0.48)
  learning_epochs: 5
  mini_batches: 4

  discount_factor: 0.99
  lambda: 0.95

  learning_rate: 1e-3
  learning_rate_scheduler: "KLAdaptiveRL"
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01

  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True

  entropy_loss_coefficient: 0.01
  value_loss_coefficient: 1.0

  stopping_kl_threshold: 0.0

  mixed_precision: True

  state_preprocessor: "RunningStandardScaler"
  state_preprocessor_kwargs: None

  value_preprocessor: "RunningStandardScaler"
  value_preprocessor_kwargs: None

  experiment:
    write_interval: 100
    checkpoint_interval: "auto"
