task_name: "newton_idle"
device: "cuda"
policy: "MlpPolicy"
seed: 14321

n_envs: 2048
timesteps_per_env: 100_000
base_lr: 3e-4
episode_length: 2000 # 20 seconds of real time (2000 * 0.01 = 20)

delay:
  enabled: False
  obs_delay_range: [1, 8] # sample range of time steps to delay the observations by
  act_delay_range: [1, 2] # sample range of time steps to delay the actions by
  instant_rewards: False # should the rewards be calculated on the brain or remote actor?

ppo:
  n_steps: 64 # 0.64 seconds of real time (64 * 0.01 = 0.64)
  batch_size: 131_072
  n_epochs: 5

  gamma: 0.99
  gae_lambda: 0.95

  clip_range: 0.2
  clip_range_vf: None

  normalize_advantage: True

  ent_coef: 0.0
  vf_coef: 0.5

  max_grad_norm: 1.0
  use_sde: False
  sde_sample_freq: -1

  target_kl: None
