robot_name: newton
robot_type: quadruped

# Actuators
actuators:
  lstm: # of the input (i.e. the motor; before applying any gear ratio)
    model_path: assets/newton/models/lstm.pth
    model_params:
      hidden_size: 32
      num_layers: 1

  mlp:
    model_path: assets/newton/models/mlp.pth
    scaler_params_path: assets/newton/models/mlp_scaler.json

  dc: # of the input (i.e. the motor; before applying any gear ratio)
    effort_saturation:
      FL_HAA: 0.25
      FR_HAA: 0.25
      HL_HAA: 0.25
      HR_HAA: 0.25
      FL_HFE: 0.25
      FR_HFE: 0.25
      HL_HFE: 0.25
      HR_HFE: 0.25
      FL_KFE: 0.25
      FR_KFE: 0.25
      HL_KFE: 0.25
      HR_KFE: 0.25

    gains:
      FL_HAA:
        p: 20.0
        d: 0.5
      FR_HAA:
        p: 20.0
        d: 0.5
      HL_HAA:
        p: 20.0
        d: 0.5
      HR_HAA:
        p: 20.0
        d: 0.5
      FL_HFE:
        p: 20.0
        d: 0.2
      FR_HFE:
        p: 20.0
        d: 0.2
      HL_HFE:
        p: 20.0
        d: 0.2
      HR_HFE:
        p: 20.0
        d: 0.2
      FL_KFE:
        p: 20.0
        d: 0.05
      FR_KFE:
        p: 20.0
        d: 0.05
      HL_KFE:
        p: 20.0
        d: 0.05
      HR_KFE:
        p: 20.0
        d: 0.05

# Kinematics
joints:
  fixed:
    FL_HAA: False
    FR_HAA: False
    HL_HAA: False
    HR_HAA: False
    FL_HFE: False
    FR_HFE: False
    HL_HFE: False
    HR_HFE: False
    FL_KFE: False
    FR_KFE: False
    HL_KFE: False
    HR_KFE: False

  gear_ratios:
    FL_HAA: 9
    FR_HAA: 9
    HL_HAA: 9
    HR_HAA: 9
    FL_HFE: 9
    FR_HFE: 9
    HL_HFE: 9
    HR_HFE: 9
    FL_KFE: 9
    FR_KFE: 9
    HL_KFE: 9
    HR_KFE: 9

  limits: # of the output (i.e. the joint itself, after applying any gear ratio)
    positions: # deg
      FL_HAA: [-45, 45]
      FR_HAA: [-45, 45]
      HL_HAA: [-45, 45]
      HR_HAA: [-45, 45]
      FL_HFE: [-90, 90]
      FR_HFE: [-90, 90]
      HL_HFE: [-90, 90]
      HR_HFE: [-90, 90]
      FL_KFE: [-175, 175]
      FR_KFE: [-175, 175]
      HL_KFE: [-175, 175]
      HR_KFE: [-175, 175]

    velocities: # deg/s
      FL_HAA: 5440
      FR_HAA: 5440
      HL_HAA: 5440
      HR_HAA: 5440
      FL_HFE: 5440
      FR_HFE: 5440
      HL_HFE: 5440
      HR_HFE: 5440
      FL_KFE: 5440
      FR_KFE: 5440
      HL_KFE: 5440
      HR_KFE: 5440

    efforts: # Nm
      FL_HAA: 3.6
      FR_HAA: 3.6
      HL_HAA: 3.6
      HR_HAA: 3.6
      FL_HFE: 3.6
      FR_HFE: 3.6
      HL_HFE: 3.6
      HR_HFE: 3.6
      FL_KFE: 3.6
      FR_KFE: 3.6
      HL_KFE: 3.6
      HR_KFE: 3.6
