robot_name: newton
robot_type: quadruped

# Kinematics
joints:
  constraints:
    FR_HAA: [-45, 45]
    FL_HAA: [-45, 45]
    HR_HAA: [-45, 45]
    HL_HAA: [-45, 45]
    FR_HFE: [-90, 90]
    HR_HFE: [-90, 90]
    FL_HFE: [-90, 90]
    HL_HFE: [-90, 90]
    FR_KFE: [-175, 175]
    FL_KFE: [-175, 175]
    HR_KFE: [-175, 175]
    HL_KFE: [-175, 175]