outputs: ["console", "file"] # "console", "file"
levels: # "debug", "info", "warning", "error", "critical"
  file: "debug"
  console: "warning"

format:
  date: False
  time: True
  level: True
  source: True