# TODO: Revamp the randomization config to be closer to how the DomainRandomizer works. It's mainly a question of removing some properties and only keeping the ones that are actually used.

randomize: True
randomization_params:
  friction_range: [0.5, 1.25]
  randomize_base_mass: False
  added_mass_range: [-1., 1.]
  push_robots: True
  push_force_xy: [0.5, 1.5]