db:
  influxdb:
    operator_token: "uQ_ieE7aueZXIU89qJmA-PweROyypNlsKPVpd8P-QM2iQ6txbM5mHK0oNNUdrKThPwTRFkPpHU6qew7AT_eZlw=="
    token: "4njHBuJeJRl1dbyLLhRV-PiYwtT8Kbbi-AOfiPZ6ns_bji0XHrdOOPwOMayTBpFb1BdAMKuTnqQfriW_dUmh9Q=="