physics_dt: 0.002500 # 400 Hz
control_dt: 0.020000 # 50 Hz
rendering_dt: 0.002500
stage_units_in_meters: 1.0
backend: torch
device: cuda

defaults:
  physics_material:
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.0

  # TODO: Add gravity as a config parameter

# the following overrides what is in assets/physics.usd
sim_params:
  substeps: 1
  solver_type: 1 # 0: PGS, 1: TGS
  enable_stabilization: True # true for a 2nd pass to stabilize fast-moving objects
  enable_scene_query_support: False # true to interact with the scene with the mouse (doesn't work with GPU dynamics)
  enable_enhanced_determinism: False # true for deterministic simulation, more computationally expensive
  disable_contact_processing: False # helpful when creating contact reporting over limited number of objects in the scene

  use_fabric: True # true for fabric, NVIDIA's fast interop layer between Hydra & PhysX; false for USD only
  enable_ccd: False # true for continuous collision detection, needs to be enabled on each rigid body & pair filter

  # Solver parameters
  min_position_iteration_count: 1
  max_position_iteration_count: 255
  min_velocity_iteration_count: 0
  max_velocity_iteration_count: 255

  # GPU buffers

  use_gpu_pipeline: True # true for GPU dynamics (i.e. deformables)
  gpu_max_rigid_contact_count: 2097152
  gpu_max_rigid_patch_count: 655360
  gpu_found_lost_pairs_capacity: 16776216
  gpu_found_lost_aggregate_pairs_capacity: 107701464
  gpu_total_aggregate_pairs_capacity: 4194304
  gpu_max_soft_body_contacts: 1024 # Soft body contacts are not used for Newton-related sims, so we keep it low
  gpu_max_particle_contacts: 1024 # Particle contacts are not used for Newton-related sims, so we keep it low
  gpu_heap_capacity: 134217728
  gpu_temp_buffer_capacity: 33554432
  gpu_max_num_partitions: 8